blog/urls.py
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.blog, name='blog'),
    path('posts/<int:post_id>/post_detail', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/comentarios', views.comentar, name='comentarios'),
    path('posts/comentarios/<int:post_id>', views.comentar_post, name='comentar_post_htmx'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('exemplos/', include('exemplos.urls')),
    path('contas/', include('autenticacao.urls')),
    path('contato/', include('contato.urls')),
    path('cursos/', include('cursos.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('criar_conta/', include('contas.urls')),
    path('accounts/', include('allauth.urls')),
    path('quiz/', include('quiz.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
'''

1. Instalar https://pypi.org/project/django-social-share/
2. https://www.tutorialspoint.com/how-to-add-social-share-buttons-in-django

'''



from ckeditor.fields import RichTextField
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from contas.models import Perfil

# Create your models here.

class Post(models.Model):
    autor = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=255)
    subtitulo = models.CharField(max_length=255)
    imagem_capa = models.ImageField(null=True, blank=True, upload_to='static/blog/')
    data_publicacao = models.DateField()
    tempo_leitura = models.CharField(max_length=2, default=30)

    def __str__(self):
        return self.titulo


class Tag(models.Model):
    nome = models.CharField(max_length=50)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return self.nome


class Assunto(models.Model):
    nome = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return self.nome


class Situacao(models.Model):
    nome = models.CharField(max_length=50)
    posts = models.ManyToManyField(Post, through='PostSituacao', through_fields=('situacao', 'post'))

    def __str__(self):
        return self.nome


class PostSituacao(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    situacao = models.ForeignKey(Situacao, on_delete=models.CASCADE)
    data = models.DateField(null=True, blank=True)

    class Meta:
        unique_together = ['post', 'situacao']


class Topico(models.Model):
    conteudo = RichTextUploadingField(blank=True, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.conteudo


class Comentario(models.Model):
    texto = models.TextField(max_length=1024)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.texto

blog/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from .models import Post, Comentario


def home(request):
    posts = Post.objects.order_by('-data_publicacao')[:5]
    context = {
        'posts': posts
    }
    return render(request, 'blog/home.html', context)


def post_detail(request, post_id):
    post = Post.objects.get(pk=post_id)
    context = {
        'post': post
    }
    return render(request, 'blog/post_detail.html', context)

def blog(request):
    posts = Post.objects.order_by('-data_publicacao')[:5]
    context = {
        'posts': posts
    }
    return render(request, 'blog/blog.html', context)

def comentar(request, post_id):
    comentario = request.POST['comentario']
    perfil = User.objects.all().first().perfil
    post = Post.objects.get(pk=post_id)

    comentario = Comentario(texto=comentario, perfil=perfil, post=post)
    comentario.save()

    context = {
        'post': post
    }

    return render(request, 'blog/post_detail.html', context)

def comentar_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    comentarios = Comentario.objects.filter(post=post)
    return render(request, "social/modal_comentar.html", { 'post': post, 'comentarios':comentarios })

blog/templates/blog/blog.html
{% extends "blog_base.html" %}
{% load static %}
{% block content %}
    <div class="col-xl-6">
        {% for post in posts %}
            {% include "fragments/card_base.html" with post=post %}
            <div class="my-3"></div>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/home.html
{% extends "blog_base.html" %}
{% load static %}
{% block title %} Academia Python {% endblock %}

{% block content %}
    <div class="col-xl-8">
        <div class="row">
            <div class="col-lg-8 d-flex">
                {% include "fragments/card_base.html" with post=posts.0 %}
            </div>

            <div class="col-lg-4 d-none d-lg-flex" hx-get="quiz/" hx-trigger="load">
                {% include 'quiz/quiz.html' %}
            </div>

        </div>

        <hr class="my-4">

        <div class="container bg-dark py-3 d-flex justify-content-center rounded">
            <span>
                <h1 class="text-info">Posts recentes</h1>
            </span>
        </div>

        <hr class="my-4">

        <div class="row row-cols-1 row-cols-md-2 g-4">
            {% for post in posts|slice:"1:5" %}
                <div class="col d-flex">
                    {% include "fragments/card_base.html" with post=post %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include 'fragments/footer.html' %}
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog_base.html" %}
{% load static %}

{% block carousel %} {% endblock %}

{% block content %}

<div class="col-xl-8 border-start border-end">
    <hr class="my-5">

    <div class="container-fluid">
        <div class="flex-row d-flex my-2">
            <h1>{{ post.titulo }}</h1>

            <span class="d-flex justify-content-center align-items-center ms-5">

               <a href="#" class="text-decoration-none text-dark">
                   <span class="ms-5"
                         data-bs-toggle="tooltip"
                         data-bs-placement="top"
                         title="Compartilhar no Instagram">

                    <i class="fa-brands fa-instagram-square fa-2xl"></i>
                    </span>
                </a>

               <a href="#" class="text-decoration-none text-dark">
                   <span class="ms-3"
                         data-bs-toggle="tooltip"
                         data-bs-placement="top"
                         title="Compartilhar no Facebook">

                        <i class="fa-brands fa-facebook fa-2xl"></i>
                    </span>
               </a>

               <a href="#" class="text-decoration-none text-dark">
                   <span class="ms-3"
                         data-bs-toggle="tooltip"
                         data-bs-placement="top"
                         title="Compartilhar no Instagram">

                       <i class="fa-brands fa-twitter fa-2xl"></i>
                    </span>
               </a>

               <a href="#" class="text-decoration-none text-dark">
                   <span class="ms-3"
                         data-bs-toggle="tooltip"
                         data-bs-placement="top"
                         title="Compartilhar no Instagram">

                       <i class="fa-solid fa-link fa-2xl"></i>
                    </span>
               </a>

           </span>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="d-flex flex-row align-items-center">
                <div class="rounded-circle d-flex justify-content-center
                    align-items-center avatar">
                    <img src="{{ post.autor.foto.url }}"
                        style="heigt:85px; width:85px"
                        class="rounded-circle">
                </div>

                <p class="mb-0">
                    <span class="text-muted justify-content-center">

                        <span class="mx-2 h5">
                            {{post.autor}}
                        </span>

                        <span>
                            <i class="fa-solid fa-clock"></i>
                            <span>
                                {{ post.tempo_leitura }}Min
                            </span>
                        </span>

                        <br>

                        <span class="mx-2"> <i class="fa-solid fa-tags"></i> </span>

                        {% for tag in post.tag_set.all %}
                            <span>
                                <a href="#" class="text-decoration-none text-muted"> #{{ tag.nome }} </a>
                            </span>
                        {% endfor %}
                        <br>

                         <span class="mx-2">
                             {{post.subtitulo}}
                        </span>

                    </span>
                </p>

            </div>
        </div>
    </div>


    <hr class="my-5">

    <article class="fs-4 px-lg-5 mx-lg-2">
        {% for topico in post.topico_set.all %}
            {{ topico.conteudo|safe }}
            <br />
        {% endfor %}
    </article>

    <hr class="my-5">

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="d-flex justify-content-md-start justify-content-sm-center">

                    <div class="span me-3 btn">
                        <i class="fa-solid fa-heart fa-2xl"></i> Curtir
                    </div>

                    {% include 'social/btn_comentar_htmx.html' %}

                </div>
            </div>
        </div>
    </div>
</div>

<div id="modals-here"></div>


{% include 'social/comentar_modal.html' %}

{% endblock %}


{% block footer %}
    {% include 'fragments/footer.html' %}
{% endblock %}